# Tomcat Server
server:
  port: 8080

# Logger
logging.level:
  web: DEBUG
  '[com.comit.users]': DEBUG
  
spring:

# Database Settings
  datasource: 
    url: jdbc:mysql://localhost:3306/fitnessdb
    username: root
    password: Sai08deepu!